export default {
    bg1: require("../images/bg-home1.jpg"),
    bg2: require("../images/bg-home2.jpg"),
    bg3: require("../images/bg-home3.jpg"),
    logo1: require("../images/logo.png"),
    logo2: require("../images/logo-alt.png"),
    menu: require("../images/menu.png"),
    deal1: require("../images/219.png"),
    deal2: require("../images/249.png"),
    menuSide: require("../images/menu-side.jpg"),
    flavors: require("../images/flavors.png"),
    buffalo: require("../images/buffalo.png"),
    garlicParmesan: require("../images/garlic-parmesan.png"),
    saltedEgg: require("../images/Salted-Egg.png"),
    alacarte: require("../images/menu-alacarte.png"),
    alacarteSide: require("../images/alacarte-side.jpg"),
    pastaMenu: require("../images/menu-pasta.png"),
    addonsMenu: require("../images/menu-addons.png"),
    othersMenu: require("../images/menu-others.png"),
    pastaPic: require("../images/pasta.jpg"),
    othersPic: require("../images/others.jpg"),
    addonsPic: require("../images/add-ons.jpg"),
    ambiencePic: require("../images/ambience.jpg"),
    forGallery1: require("../images/Gallery/_DSC7191.jpg"),
    forGallery2: require("../images/Gallery/_DSC7213.jpg"),
    forGallery3: require("../images/Gallery/_DSC7256.jpg"),
    forGallery4: require("../images/Gallery/_DSC7262.jpg"),
    forGallery5: require("../images/Gallery/_DSC7268.jpg"),
    forGallery6: require("../images/Gallery/_DSC7270.jpg"),
    forGallery7: require("../images/Gallery/_DSC7300.jpg"),
    forGallery8: require("../images/Gallery/_DSC7302.jpg"),
    forGallery9: require("../images/Gallery/_DSC7304.jpg"),
    forGallery10: require("../images/Gallery/wings lokal-10.jpg"),
    forGallery11: require("../images/Gallery/wings lokal-11.jpg"),
    forGallery12: require("../images/Gallery/wings lokal-12.jpg"),
    forGallery13: require("../images/Gallery/wings lokal-18.jpg"),
    forGallery14: require("../images/Gallery/wings lokal-19.jpg"),
    forGallery15: require("../images/Gallery/wings lokal-26.jpg"),
    forGallery16: require("../images/Gallery/wings lokal-28.jpg"),
    forGallery17: require("../images/Gallery/wings lokal-30.jpg"),
    forGallery18: require("../images/Gallery/wings lokal-31.jpg"),
    forGallery19: require("../images/Gallery/wings lokal-33.jpg"),
    forGallery20: require("../images/Gallery/wings lokal-34.jpg"),
    forGallery21: require("../images/Gallery/wings lokal-35.jpg"),
    forGallery22: require("../images/Gallery/wings lokal-37.jpg"),
    forGallery23: require("../images/Gallery/wings lokal-40.jpg"),
    forGallery24: require("../images/Gallery/wings lokal-41.jpg"),
    forGallery25: require("../images/Gallery/wings lokal-48.jpg"),
    forGallery26: require("../images/Gallery/wings lokal-5.jpg"),
    forGallery27: require("../images/Gallery/wings lokal-55.jpg"),
    forGallery28: require("../images/Gallery/wings lokal-7.jpg"),
    forGallery29: require("../images/Gallery/wings lokal-8.jpg"),
    forGallery30: require("../images/Gallery/wings lokal-9.jpg"),
    forGallery31: require("../images/Gallery/wings lokal.jpg"),
}